### ISSUE TITLE
Compute weather informations

### ISSUE THREAD

**Issue by arnaudDup** [antitoine/ADAEPFL-Project#14]
under task #7.
Compute informations about weather, altitude, ... on selected races

**Comment by antitoine** [comment]
It is done right ? @arnaudDup 
You have marathon Lausanne 1999-2016 weathers information and some other for runners ?

**Comment by arnaudDup** [comment]
Here the following races where we have weather data :  'Lausanne Marathon', '20km de Lausanne' , 'Morat-Fribourg' , 'Course de l\'Escalade, Genève' ,  'Sierre-Zinal, Sierre',  'Zermatt Marathon, Zermatt'
