### ISSUE TITLE
Study different tools for visualization

### ISSUE THREAD

**Issue by arnaudDup** [antitoine/ADAEPFL-Project#4]
Make some prototypes on new technologies.
The idea is to choose the most efficient one and have some samples to share code to other members of team.

**Comment by antitoine** [comment]
Ideas from [d3/Gallery](https://github.com/d3/d3/wiki/Gallery):
- Visualization of a single runner: [http://square.github.io/crossfilter/](http://square.github.io/crossfilter/)
![687474703a2f2f64336a732e6f72672f65782f63726f737366696c7465722e706e67](https://cloud.githubusercontent.com/assets/10686594/21521891/2f8c6e92-cd01-11e6-9fc4-88bf3b251a97.png)
- Visualization of generals performances in Marathon Lausanne (1999-2016): [http://bl.ocks.org/rkirsling/33a9e350516da54a5d4f](http://bl.ocks.org/rkirsling/33a9e350516da54a5d4f)
![687474703a2f2f626c2e6f636b732e6f72672f726b6972736c696e672f7261772f33336139653335303531366461353461356434662f7468756d626e61696c2e706e67](https://cloud.githubusercontent.com/assets/10686594/21521931/80d44194-cd01-11e6-840c-f05dc6b6c1eb.png)
- Visualization of ranks of runners in Marathon Lausanne (1999-2016): [http://www.visualcinnamon.com/2015/01/the-top-2000-equalizer-songs.html](http://www.visualcinnamon.com/2015/01/the-top-2000-equalizer-songs.html)
![top-2000-equalizer-bar-chart-square](https://cloud.githubusercontent.com/assets/10686594/21521970/cfa901c4-cd01-11e6-9a6d-68f91fe4ae60.png)
- Performances evolution of a single runner: [http://bl.ocks.org/csaladenes/ddc0b326b93ec641c84f](http://bl.ocks.org/csaladenes/ddc0b326b93ec641c84f)
![quandl](https://cloud.githubusercontent.com/assets/10686594/21522010/1a76a13e-cd02-11e6-8d94-ca156307e51a.jpg)
- Performances evolution of a single runner: [https://piratepeel.github.io/sportskills.html](https://piratepeel.github.io/sportskills.html)
![68747470733a2f2f7069726174657065656c2e6769746875622e696f2f696d672f73706f727473637265656e2e706e67](https://cloud.githubusercontent.com/assets/10686594/21522081/d6a8b964-cd02-11e6-94d5-736826620fd8.png)

**Comment by antitoine** [comment]
Very simple and works perfectly with Angular 2 : [ng2-charts](http://valor-software.com/ng2-charts/)

**Comment by arnaudDup** [comment]
https://plot.ly/javascript/  Built on top of d3.js and stack.gl, plotly.js is a high-level, declarative charting library. plotly.js ships with 20 chart types, including 3D charts, statistical graphs, and SVG maps. 

Work also in python

**Comment by antitoine** [comment]
Possible library to make the real dynamic and complex graph:
- **Vaadin Charts** / [Demo](http://demo.vaadin.com/vaadin-charts/) / [Docs](https://vaadin.com/vaadin-documentation-portlet/charts/webcomponents-api/charts-angular2.html) / [Project](https://github.com/vaadin/charts) : it seams very complex to use but very powerful. The integration with Angular will be a little bit complicated
![capture du 2017-01-11 22-26-39](https://cloud.githubusercontent.com/assets/10686594/21867250/a3c56dde-d84d-11e6-9604-073145b8e073.png)
- **ngx-charts (f.k.a. ng2d3)** / [Demo](https://swimlane.github.io/ngx-charts/) / [Docs](https://swimlane.gitbooks.io/ngx-charts/content/) / [Project](https://github.com/swimlane/ngx-charts) : less graphics, but very design and it seams easier to integrate with Angular
![capture du 2017-01-11 22-42-15](https://cloud.githubusercontent.com/assets/10686594/21867612/3f84b72e-d84f-11e6-9d6f-d6f22bb90491.png)
- **ng2-nvd3** / [Demo](http://krispo.github.io/ng2-nvd3/) / [Docs](http://krispo.github.io/angular-nvd3/#/) / [Project](https://github.com/krispo/ng2-nvd3) : an AngularJS (Angular 1) module adapted to Angular 2, it seams easier but with less features
![capture du 2017-01-11 22-43-14](https://cloud.githubusercontent.com/assets/10686594/21867641/5d70c11a-d84f-11e6-814b-9022fdf2aaeb.png)

**Comment by antitoine** [comment]
We select Plotly.js ([github](https://github.com/plotly/plotly.js) / [website](https://plot.ly/javascript/)). See notes: 
**Jupyter Notebook side**
 - Installation Jupyter Notebook (use `pip`): https://plot.ly/python/getting-started/
 - Use offline mode :
```python
import plotly
plotly.offline.init_notebook_mode()
plotly.offline.iplot(fig)
```
 - Use it https://plot.ly/ipython-notebooks/

**Plotly graph in presentation website**
 - Installation with Angular 2 done in 1b94b60fa79ad9f5bfb4a736a9dc211790d56baf 
 - Follow steps here to offline and output correctly graph: https://plot.ly/python/offline/ and http://stackoverflow.com/questions/36262748/python-save-plotly-plot-to-local-file-and-insert-into-html
If we real interactive Javascript graph, we need to write it directly in the TypeScript file following the [Plotly.js API](https://plot.ly/javascript/) like in [lausanne-1999-2016.component.ts](https://github.com/antitoine/ADAEPFL-Project/blob/1b94b60fa79ad9f5bfb4a736a9dc211790d56baf/src/app/lausanne-1999-2016/lausanne-1999-2016.component.ts) and [lausanne-1999-2016.component.html](https://github.com/antitoine/ADAEPFL-Project/blob/1b94b60fa79ad9f5bfb4a736a9dc211790d56baf/src/app/lausanne-1999-2016/lausanne-1999-2016.component.html)
