### ISSUE TITLE
Build website

### ISSUE THREAD

**Issue by asalihi** [antitoine/ADAEPFL-Project#6]
Website of project: https://antitoine.github.io/ADAEPFL-Project/

Create a website which will include two main parts:
- project presentation (introduction, description of pipeline, summary of data scheme, ...);
- results (detailed statistics for Lausanne marathon (2016), analysis of marathon over the years, final and global graph).

Website will use JavaScript libraries and, if possible, use multiple pages.

Example of website: https://sites.google.com/site/atb10kbridgerace/home

**Comment by antitoine** [comment]
We now use the angular 2 framework to get multiple pages, the branch development is available here: [website](https://github.com/antitoine/ADAEPFL-Project/tree/website) (nodejs with npm is required)

The production website is available here: [https://antitoine.github.io/ADAEPFL-Project/](https://antitoine.github.io/ADAEPFL-Project/)

The procedure to deploy the website is describe here: [Readme - Section deploying](https://github.com/antitoine/ADAEPFL-Project/tree/website#deploying-to-github-pages)
