### ISSUE TITLE
Study of Lausanne marathons (1999-2016)

### ISSUE THREAD

**Issue by asalihi** [antitoine/ADAEPFL-Project#8]
This part of the study will focus on all runnings of Lausanne Marathon, between 1999 and 2016. 

Examples of analysis to be done:
- evolution following the years (performance);
- potential effects of groups on the performance of runners (comparison between single runner/groups of runners);
- global visualisation including weather, sex of participants, distance, speed, ...;
- influence of the weather (this analysis will be detailed in #5).

**Comment by antitoine** [comment]
@asalihi nothing to add ? Just review #17  ?
